[package]
name = "drost"
version = "0.1.0"
authors = ["Scotow <contact@scotow.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.3", features = ["full"] }
hyper = { version = "0.14", features = ["stream"] }
routerify = "2.0"
futures = "0.3"
sqlx = { version = "0.5", default-features = false, features = ["runtime-tokio-native-tls", "sqlite", "macros"] }
tokio-util = { version = "0.6", default-features = false, features = ["io", "compat"] }
async-tar = "0.3"
lazy_static = "1.4"
rand = "0.8"
regex = "1.4"