name: Docker

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
  docker-debian:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: scotow/dropit/dropit
          dockerfile: debian.Dockerfile
          tag_with_ref: true
          tag_with_sha: true
          tags: debian,debian-latest,latest
          push: true